In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer , SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Most accuracy_score Technique =  constant , fill_value = 99  (SimpleImputer)

In [2]:
df = pd.read_csv("C:/Users/patan/DS/Machine Learning/Dataset/train.csv", usecols = ['Age','Fare','Survived'])
print(df.shape)
df.head()

(891, 3)


Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [3]:
X = df.drop(columns = "Survived") 

In [4]:
y = df["Survived"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2,shuffle=False )  # shuffle=False is Used for the split data into to 
X_train     # two Sequatial part and random_state split into two random part 

Age      Fare
0    22.0    7.2500
1    38.0   71.2833
2    26.0    7.9250
3    35.0   53.1000
4    35.0    8.0500
..    ...       ...
707  42.0   26.2875
708  22.0  151.5500
709   NaN   15.2458
710  24.0   49.5042
711   NaN   26.5500

[712 rows x 2 columns]

In [6]:
y_test

712    1
713    0
714    0
715    0
716    1
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 179, dtype: int64

#  KNN Imputation

In [7]:
knn  = KNNImputer(n_neighbors=6 )   # add_indicator=True

In [8]:
X_train_ft = knn.fit_transform(X_train)
X_test_ft = knn.transform(X_test)
X_train_ft

array([[22.    ,  7.25  ],
       [38.    , 71.2833],
       [26.    ,  7.925 ],
       ...,
       [34.5   , 15.2458],
       [24.    , 49.5042],
       [52.    , 26.55  ]])

In [9]:
new_df = pd.DataFrame(X_train_ft , columns = ["Imputed_Age" , "Imputed_Fare" ])
# new_df = pd.DataFrame(X_train_ft , columns = ["Imputed_Age" , "Imputed_Fare" ,"Missing" ])

In [10]:
new_df

Imputed_Age  Imputed_Fare
0           22.0        7.2500
1           38.0       71.2833
2           26.0        7.9250
3           35.0       53.1000
4           35.0        8.0500
..           ...           ...
707         42.0       26.2875
708         22.0      151.5500
709         34.5       15.2458
710         24.0       49.5042
711         52.0       26.5500

[712 rows x 2 columns]

In [11]:
lr = LogisticRegression()
lr.fit(X_train_ft, y_train)
y_prediction_1 =lr.predict(X_test_ft)
accuracy_score(y_test,y_prediction_1)

0.6871508379888268

In [12]:
# accuracy_score =  0.6558988764044944

#  Simpule imputer accuracy_score  (Mean)

In [13]:
si = SimpleImputer()  # add_indicator=True

In [14]:
X_train_si = si.fit_transform(X_train)
X_test_si = si.transform(X_test)

In [15]:
X_train_si

array([[22.        ,  7.25      ],
       [38.        , 71.2833    ],
       [26.        ,  7.925     ],
       ...,
       [30.03053097, 15.2458    ],
       [24.        , 49.5042    ],
       [30.03053097, 26.55      ]])

In [16]:
lr = LogisticRegression()

In [17]:
lr.fit(X_train_si, y_train)
y_prediction_2 = lr.predict(X_test_si)
accuracy_score(y_test, y_prediction_2)

0.6871508379888268

In [18]:
# accuracy_score = 0.7039106145251397

#  Simpule imputer accuracy_score (Median)

In [19]:
si = SimpleImputer(strategy = "median")  # add_indicator=True

In [20]:
X_train_si2 = si.fit_transform(X_train)
X_test_si2 = si.transform(X_test)
X_train_si2

array([[22.    ,  7.25  ],
       [38.    , 71.2833],
       [26.    ,  7.925 ],
       ...,
       [28.    , 15.2458],
       [24.    , 49.5042],
       [28.    , 26.55  ]])

In [21]:
lr = LogisticRegression()

In [22]:
lr.fit(X_train_si2,y_train)

LogisticRegression()

In [23]:
y_pred_3  = lr.predict(X_test_si2)

In [24]:
accuracy_score(y_test, y_pred_3)

0.6871508379888268

In [25]:
# accuracy_score = 0.7039106145251397

#  Simpule imputer accuracy_score (most_frequent)

In [26]:
si =  SimpleImputer(strategy = "most_frequent") # add_indicator=True
si

SimpleImputer(strategy='most_frequent')

In [27]:
X_train_si3 = si.fit_transform(X_train)
X_test_si3 = si.transform(X_test)

In [28]:
lr = LogisticRegression()
lr.fit(X_train_si3,y_train)
y_pred_4 = lr.predict(X_test_si3)
accuracy_score(y_test ,y_pred_4)

0.6927374301675978

In [29]:
# accuracy_score = 0.7039106145251397

#  Simpule imputer accuracy_score (constant)

In [30]:
si = SimpleImputer(strategy = "constant" , fill_value = -1 ) # add_indicator=True

In [31]:
X_train_si4  = si.fit_transform(X_train)
X_test_si4 = si.transform(X_test)

In [32]:
lr = LogisticRegression()
lr.fit(X_train_si4 , y_train)
y_pred_5 = lr.predict(X_test_si4)
accuracy_score(y_test,y_pred_5 )

0.6927374301675978

In [33]:
# accuracy_score = 0.7039106145251397    fill_value = 99 == 0.7150837988826816

#   DataFrame with Zero nan/null value

In [34]:
new_df.shape

(712, 2)

In [35]:
y_train.shape

(712,)

In [36]:
data = pd.concat([y_train,new_df ] , axis = 1)
print(data.isnull().sum())
data

Survived        0
Imputed_Age     0
Imputed_Fare    0
dtype: int64


Survived  Imputed_Age  Imputed_Fare
0           0         22.0        7.2500
1           1         38.0       71.2833
2           1         26.0        7.9250
3           1         35.0       53.1000
4           0         35.0        8.0500
..        ...          ...           ...
707         1         42.0       26.2875
708         1         22.0      151.5500
709         1         34.5       15.2458
710         1         24.0       49.5042
711         0         52.0       26.5500

[712 rows x 3 columns]